# PUIE experiment configuration

# ------------ general ------------
name: PUIE_abl_model_e_freq_only
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 100

# ------------ datasets ------------
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: data/Mixed/train/gt
    dataroot_lq: data/Mixed/train/input
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend: { type: disk }

    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    # 固定 128×128 训练
    mini_batch_sizes: [8]
    iters: [300000]
    gt_size: 128
    gt_sizes: [128]

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: data/Mixed/test/gt
    dataroot_lq: data/Mixed/test/input
    io_backend: { type: disk }

# ------------ network ------------
network_g:
  type: PUIE
  in_channels: 3
  out_channels: 3
  n_feat: 40
  stage: 1
  num_blocks: [1, 2, 2]

  # 消融开关（Model-e：Frequency-only，开启 BMS + SFDE Frequency，关闭 SFDE Spatial）
  use_bms: true
  use_sfde_spatial: false
  use_sfde_token: true
  use_freq: true
  use_moe: false

  # 退化感知
  tok_dim: 128
  deg_ch: 48
  share_deg: true
  router_tau: 0.7

  # DnCNN 去噪（建议开启）
  use_dncnn_shallow: true
  use_dncnn_bottleneck: true
  dncnn_depth: 6
  dncnn_alpha_max: 0.6

  # IGAB 内部去噪（建议关闭）
  use_block_denoiser: false

# ------------ path ------------
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# ------------ training ------------
train:
  total_iter: 150000
  warmup_iter: -1
  use_grad_clip: true
  use_amp: true

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [46000, 104000]
    restart_weights: [1, 1]
    eta_mins: [0.0003, 0.000001]

  mixing_augs:
    mixup: false           # 混合退化下建议关闭
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: Adam
    lr: !!float 2e-4
    betas: [0.9, 0.999]

  # 更稳的无标签混合退化损失组合
  pixel_opt:
    type: CharbonnierLoss
    loss_weight: 1.0
    reduction: mean
# ------------ validation ------------
val:
  window_size: 4
  val_freq: !!float 9999999999
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false

# ------------ logging ------------
logger:
  print_freq: 500
  save_checkpoint_freq: !!float 1e3
  use_tb_logger: true
  wandb:
    project: low_light
    resume_id: ~

# ------------ dist ------------
dist_params:
  backend: nccl
  port: 29500
